user nginx;
worker_processes auto;
pid /run/nginx.pid;
include /usr/share/nginx/modules/*.conf;
error_log /dev/stderr;

events {
  worker_connections  1024;
}

http {
  access_log    /dev/stdout;

  sendfile               on;
  gzip                   on;
  gzip_types             text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;
  types_hash_max_size    4096;
  client_max_body_size   100M;
  tcp_nopush             on;
  tcp_nodelay            on;
  keepalive_timeout      65;

  include             /etc/nginx/mime.types;
  default_type        application/octet-stream;

  include /etc/nginx/conf.d/php-fpm.conf;

  fastcgi_cache_path /var/cache/nginx levels=1:2 keys_zone=WORDPRESS:100m max_size=1g inactive=60m use_temp_path=off;
  fastcgi_cache_key "$scheme$request_method$host$request_uri";
  fastcgi_cache_use_stale error timeout updating invalid_header http_500 http_503;
  fastcgi_ignore_headers Cache-Control Expires Set-Cookie;

  server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;
    root /app/web;
    index index.php;

    fastcgi_hide_header X-Powered-By;

    set_real_ip_from 172.17.0.1;
    real_ip_header X-Forwarded-For;

    set $skip_cache 0;
  
    # POST requests and queries with args should always go to PHP
    if ($request_method = POST) {
        set $skip_cache 1;
    }   
    if ($query_string != "") {
        set $skip_cache 1;
    }   
  
    # Don't cache specific WP URLs (admin, login, xmlrpc, sitemaps)
    if ($request_uri ~* "/wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml") {
        set $skip_cache 1;
    }   
  
    # Don't cache for logged-in users or recent commenters
    if ($http_cookie ~* "comment_author|wordpress_logged_in|wp-postpass_|wordpress_no_cache") {
        set $skip_cache 1;
    }

    location / {
      try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
      # Ensure file exists before sending to FastCGI
      try_files $uri =404;

      # Directives to apply the FastCGI cache
      fastcgi_cache WORDPRESS;
      fastcgi_cache_valid 200 301 302 60m;
      fastcgi_cache_bypass $skip_cache;
      fastcgi_no_cache $skip_cache;

      # Useful header to verify cache hits in your browser dev tools
      add_header X-FastCGI-Cache $upstream_cache_status;

      # Pull in your existing PHP-FPM upstream configs (e.g., fastcgi_pass, fastcgi_index)
      include /etc/nginx/default.d/php.conf;
    }

    location /app/themes/chrisn-xyz/dist/ {
        allow all;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    location /app/themes/ {
      deny all;
    }

    location /app/uploads/ {
    }
  }
}
