apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chrisn-xyz.fullname" . }}-wp-uploads
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "chrisn-xyz.labels" . | nindent 4 }}
    {{- toYaml .Values.uploadsStoragePvcLabels | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.uploadsStorageRequest }}"
  {{- if .Values.uploadsStorageClassName }}
  storageClassName: "{{ .Values.uploadsStorageClassName }}"
  {{- end }}
